[Telegram]
# Application Name
Namespace = "MyApp"
# Secret Token for OTP
Secret = "AAHKeFFD5R9mAg8pRfSKXfFkg05Mbo0NS3Q"
# Telegram Bot Key Input Here
BotKey = "1779011813:AAHKeFFD5R9mAg8pRfSKXfFkg05Mbo0NS3Q"

[WhiteList]
WhiteDomainEnabled = true
WhiteDomain = "@qq.com,@hotmail.com"
WhiteEmailEnabled = true

# Bot Program DB Connect Info
[MysqlDB]
Host = "127.0.0.1"
Port = 3306
Username = "root"
Password = "root"
DBName = "strangerbot"
# The following configuration can be left unchanged
Charset = "utf8"
MaxOpenConns = 1000
MaxIdleConns = 1000
ConnMaxLifetime = 10

# OTP Redis Conf
[RedisConf]
Host = "127.0.0.1"
Port = "6379"
Username = ""
Password = "test123"
MaxActive = 100
MaxIdle = 10
TimeoutSeconds = 10
KeyPrefix = "OTP"

[OTPConf]
# otp time to live seconds
OTPTTL = 300
# otp max attempts
OTPMaxAttempts = 500
# otp len
OTPMaxLen = 6

[EmailOTP]
# email subject
Subject = "MyApp Email verification"
# email send template
Template = "static/smtp.tpl"
# email template type default:html
TemplateType = "html"
# email smtp config
Config = '''
    {
        "Host": "smtp.sendgrid.net",
        "Port": 25,
        "AuthProtocol": "",
        "User": "apikey",
        "Password": "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",
        "FromEmail": "noreply@fiverr.chat",
        "MaxConns": 10,
        "Sendtimeout": 5
    }
'''
